### PR TITLE
tools/suit_v4: fix flake8 issue with sign-04.py script

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is fixing all flake8 issues reported by `make static-test` on the sign-04.py script.

Note that there is this comment at the beginning of the script:
```
It is expected that C and C++ parser implementations will be written
against this script, so it does not adhere to PEP8 in order to maintain
similarity between the naming in this script and that of C/C++ implementations.
```
But since it's now expected that this script should go as is in RIOT upstream, we should at least fix the reported flake8 issues.

Maybe the comment could be removed?

### Testing procedure

- `make static-test` should not report flake8 issues on this script
- the SUIT workflow is still working

### Issues/PRs references

This is based on #23 for simplicity.

### CODE REVIEW

**Comment by aabadie** [comment]
rebased, now that #23 is merged.

**Comment by kaspar030** [comment]
> Maybe the comment could be removed?

Isn't it referring to the variable naming?

**Comment by aabadie** [comment]
> Isn't it referring to the variable naming?

You are right. I guess we can keep it then.

**Comment by kaspar030** [comment]
Only style changes, ACK.

**Comment by aabadie** [comment]
Thanks @kaspar030!

**Pull request merged**
