### PR TITLE
Pr option block cleanup

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

This PR  cleans up some duplicated code. If changes are agreed I will open a PR on master for the first commit adding the block2 wrapper.

### Testing procedure

Follow [examples/suit_update/README.md](https://github.com/future-proof-iot/RIOT/blob/suit-dev/examples/suit_update/README.md) everything still works.

### CODE REVIEW

**Comment by kaspar030** [comment]
> If changes are agreed I will open a PR on master for the first commit adding the block2 wrapper.

I kept this in suit/ as the change collides with @kb2ma's coap PR's...

**Comment by fjmolinas** [comment]
> I kept this in suit/ as the change collides with @kb2ma's coap PR's...

Oh, I did not know that. So what is the plan then? Wait for https://github.com/RIOT-OS/RIOT/pull/11002 to get merged? Push https://github.com/RIOT-OS/RIOT/pull/11002 merge?

Are there other dependencies in suit code?

**Comment by kb2ma** [comment]
Of course I would love to see progress toward merging RIOT-OS#11002 and the rest in the series, as shown in the last couple of comments on RIOT-OS#10732. I have time available at present for this work.

**Comment by fjmolinas** [comment]
@kb2ma great to hear that! I'll try to give it a review then!, I'll have to refresh my block-coap Knowledge before though.

**Comment by fjmolinas** [comment]
Closing in favor of #30

**Pull request closed without merging**
